### PR TITLE
Script to filter on each attribute table's column

### PR DESCRIPTION
**Pull request by nboisteault**

### CODE REVIEW

**Comment by rldhont** [comment]
Do you think they are some lack in lizmap ?
@mdouchin what do you think about this ?

**Comment by nboisteault** [comment]
It would be great if we could configurate filters for columns in the Lizmap plugin. We could activate/deactivate for every single column and we could also tell which kind of filter we want like a free field or a HTML select or a list of checkboxes for every values.

**Comment by rldhont** [comment]
@nboisteault why do you use a setTimeout ? No event when the table is ready ?

**Comment by nboisteault** [comment]
@rldhont because of https://github.com/3liz/lizmap-web-client/issues/997

**Comment by rldhont** [comment]
ok, needs to be fixed.

**Pull request merged**
