### PR TITLE
Better folder organization and script print simplify options.

### PR DESCRIPTION
**Pull request by arno974**
This pull request propose to organize all the JS Scripts into some specific folders.
Also, a new JS Script to simplify the print options is proposed.

### CODE REVIEW

**Comment by Gustry** [comment]
Thanks for your contribution @arno974 !
You would need to update your branch, scripts have been moved.
But I would appreciate if we have specific folder too.

I just added a contributing file to the repository : https://github.com/3liz/lizmap-javascript-scripts/blob/master/CONTRIBUTING.md

**Comment by arno974** [comment]
Done branch updated with your master.
I agree that regarding the number of scripts we should probably order them inside thematic folders.
I've grouped the scripts into 4 main categories (Data, Misc, Tools, UI). But there is maybe a better organization or naming...

**Comment by Gustry** [comment]
> I've grouped the scripts into 4 main categories (Data, Misc, Tools, UI). But there is maybe a better organization or naming...

Let's go like this and we will see. Thanks for improving the orga.

Links need to be updated with folders : https://github.com/arno974/lizmap-javascript-scripts
It leads to 404.

**Comment by arno974** [comment]
Thanks, done.

**Comment by Gustry** [comment]
Thanks @arno974 !

**Pull request merged**
